version: "3.7"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_hoofledger
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbdata:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    # env_file:
    # - .env
    command: [--auth]
