version: '3.7'
  mongodb:
    image: mongo:latest
    container_name: mongodb_middleware
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbdata:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    # env_file:
    # - .env
    command: [--auth]

  influxdb:
    image: influxdb:1.8
    container_name: skl_influxdb
    # restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-storage:/var/lib/influxdb
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      INFLUXDB_DB: skallar
      INFLUXDB_ADMIN_USER: influxadmin
      INFLUXDB_ADMIN_PASSWORD: pwdSKL2024
      TZ: 'America/Sao_Paulo'
 